# Generated by Django 3.2.23 on 2023-12-07 21:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField()),
                ('start_time', models.TimeField(choices=[(datetime.time(9, 0), '9:00am'), (datetime.time(11, 0), '11:00am'), (datetime.time(13, 0), '1:00pm'), (datetime.time(15, 0), '3:00pm'), (datetime.time(17, 0), '5:00pm'), (datetime.time(19, 0), '7:00pm')])),
                ('end_time', models.TimeField(blank=True, editable=False, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_name_booking', to='karting.services')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_booking', 'start_time'],
            },
        ),
    ]
