# Generated by Django 4.2.8 on 2023-12-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='message',
        ),
    ]
