# Generated by Django 4.2.8 on 2023-12-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karting', '0002_remove_booking_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.AddField(
            model_name='services',
            name='session_length',
            field=models.DurationField(null=True),
        ),
    ]
